# Generated by Django 3.0.4 on 2020-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20200413_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['prioridad']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('5', 'Urgente'), ('4', 'Alta'), ('3', 'Media'), ('2', 'Baja'), ('0', 'Nula')], default=0, max_length=7),
        ),
    ]
