# Generated by Django 3.0.4 on 2020-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20200413_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['estado', 'prioridad']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[(0, 'Abierto'), (1, 'Pendiente'), (2, 'Resuelto'), (3, 'Cerrado')], default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[(0, 'Urgente'), (1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3, max_length=7),
        ),
    ]
