# Generated by Django 3.0.4 on 2020-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20200413_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Abierto'), (1, 'Pendiente'), (2, 'Resuelto'), (3, 'Cerrado')], default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Urgente'), (1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3),
        ),
    ]
