# Generated by Django 3.0.4 on 2020-04-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_comentariosticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariosticket',
            old_name='comentario',
            new_name='texto',
        ),
    ]
