# Generated by Django 3.0.4 on 2020-04-22 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0020_rolesproyectos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolesProyectos',
            new_name='RolesProyecto',
        ),
    ]
