# Generated by Django 3.0.4 on 2020-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
