# Generated by Django 3.0.4 on 2020-05-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20200501_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10),
        ),
    ]
