# Generated by Django 3.0.4 on 2020-05-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_auto_20200502_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['fecha_creacion', '-estado']},
        ),
    ]
