# Generated by Django 3.0.4 on 2020-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ABIERTO', max_length=10),
        ),
    ]
