# Generated by Django 3.0.4 on 2020-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_proyecto_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['estado']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('1', 'Urgente'), ('2', 'Alta'), ('3', 'Media'), ('4', 'Baja')], default='BAJA', max_length=7),
        ),
    ]
