# Generated by Django 3.0.4 on 2020-04-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200413_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-estado']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('3', 'Urgente'), ('2', 'Alta'), ('1', 'Media'), ('0', 'Baja')], default='BAJA', max_length=7),
        ),
    ]
