# Generated by Django 3.0.4 on 2020-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200413_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[(3, 'Urgente'), (2, 'Alta'), (1, 'Media'), (0, 'Baja')], default=0, max_length=7),
        ),
    ]
