# Generated by Django 3.0.4 on 2020-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20200415_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('BUG', 'Bug'), ('CONSULTA', 'Consulta'), ('FEATURE REQUEST', 'Solicitud de función'), ('OTROS', 'Otros')], default='OTROS', max_length=15),
        ),
    ]
