# Generated by Django 3.0.4 on 2020-04-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_adjuntosticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjuntosticket',
            old_name='adjunto',
            new_name='fichero',
        ),
    ]
